apiVersion: intel.com/v1alpha1
kind: ClusterPolicy
metadata:
  name: gpu-policy
spec:
  resourceRegistration: dp

  health:
    coreTemperatureThreshold: 88

  dp:
    plugin: docker.io/intel/intel-gpu-plugin:0.35.0@sha256:34697f9c286857da986381595ac2a693524a83c831955247dae47dfda4d2f526
    levelzero: docker.io/intel/intel-gpu-levelzero:0.35.0@sha256:a8a0729f253de6e8e117a7ef621883a1228f7304747076dcd1446c3e18804021
    byPathMode: single
    logLevel: 4
