---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: intel-gpu-base-operator
  name: intel-gpu-base-operator-metrics-certs
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - SERVICE_NAME.SERVICE_NAMESPACE.svc
  - SERVICE_NAME.SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: intel-gpu-base-operator-selfsigned-issuer
  secretName: metrics-server-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: intel-gpu-base-operator
  name: intel-gpu-base-operator-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - intel-gpu-base-operator-webhook-service.{{ .Release.Namespace }}.svc
  - intel-gpu-base-operator-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: intel-gpu-base-operator-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: intel-gpu-base-operator
  name: intel-gpu-base-operator-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
