---
{{- if .Values.privateRegistry.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-operator-private-registry
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.privateRegistry.url (printf "%s:%s" .Values.privateRegistry.user .Values.privateRegistry.token | b64enc) | b64enc }}
{{- end }}
